"use client";

import { useEffect, useMemo, useRef, useState } from "react";

const SCRIPT_ID = "officer-semantic-loader";
const ratings = [[0,"Nie wiem"],[1,"Słabo"],[2,"Z pomocą"],[3,"Samodzielnie"],[4,"Płynnie"]];
const stop = new Set("oraz który która które których przez przed jest była było były będzie są się dla tego jako jego jej ich pod nad lub czy nie tak tym ten ta to został została zostały według w we z ze do na o od po za i a że co jak u między podczas którym której którego może ma miał miała miały być by też natomiast".split(" "));

function norm(v){return String(v||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9ąćęłńóśźż\s-]/gi," ").replace(/\s+/g," ").trim()}
function key(t){if(/^\d+$/.test(t))return t;if(t.length>=8)return t.slice(0,6);if(t.length>=6)return t.slice(0,5);return t}
function tokens(text,limit=12){const seen=new Set(),out=[];for(const t of norm(text).split(" ")){if(!t||stop.has(t)||(t.length<4&&!/^\d+$/.test(t)))continue;const k=key(t);if(seen.has(k))continue;seen.add(k);out.push(k);if(out.length>=limit)break}return out}
function lexical(transcript,point){const src=tokens(point,10);if(!src.length)return 0;const spoken=new Set(tokens(transcript,260));return src.filter(x=>spoken.has(x)).length/src.length}
function chunks(q){const kp=(q.keyPoints||[]).map(x=>x.trim()).filter(x=>x.length>15);if(kp.length>=2)return kp.slice(0,8);const body=String(q.fullAnswer||"").split(/\n+/).map(x=>x.trim()).filter(Boolean).filter(x=>!/^uzupełniono spoza kompletnej bazy|^odpowiedź:?$|^źródło uzupełnienia:|^uwaga:/i.test(x)).join("\n");const raw=body.split(/(?<=[.!?])\s+|\n+/).map(x=>x.trim()).filter(x=>x.length>12);return(raw.length?raw:kp.length?kp:[q.fullAnswer||""]).slice(0,8)}
function semScore(sim){if(!Number.isFinite(sim)||sim<=.30)return 0;if(sim>=.82)return 1;return Math.max(0,Math.min(1,(sim-.30)/.52))}
function mismatch(point,text){const nums=[...String(point).matchAll(/\b\d+[\d.,/-]*\b/g)].map(x=>x[0]);const spoken=norm(text);return nums.length>0&&nums.some(x=>!spoken.includes(norm(x)))}
function pick(qs,progress,exclude){const base=exclude&&qs.length>1?qs.filter(q=>q.id!==exclude):qs;const pool=base.flatMap(q=>Array.from({length:Math.max(1,6-(progress[q.id]?.rating??0))},()=>q));return pool[Math.floor(Math.random()*pool.length)]||base[0]||null}
function fmt(s){return`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`}
function stateFor(v){if(v>=.68)return["✅","sens pokryty","border-[#526548] bg-[#172016]"];if(v>=.40)return["🟡","częściowo","border-amber-900/50 bg-amber-950/10"];return["❌","brak / słabo","border-red-950/70 bg-red-950/10"]}

function getEngine(){
  if(window.__officerSemantic)return Promise.resolve(window.__officerSemantic);
  let script=document.getElementById(SCRIPT_ID);
  if(!script){script=document.createElement("script");script.id=SCRIPT_ID;script.type="module";script.src="/semantic-loader.js";document.head.appendChild(script)}
  return new Promise((resolve,reject)=>{
    let done=false;
    const finish=(err)=>{if(done)return;done=true;clearTimeout(timer);window.removeEventListener("officer-semantic-ready",ready);script.removeEventListener("error",fail);err?reject(err):resolve(window.__officerSemantic)};
    const ready=()=>window.__officerSemantic&&finish();
    const fail=()=>finish(new Error("Nie udało się załadować modułu semantycznego."));
    const timer=setTimeout(()=>finish(new Error("Przekroczono czas ładowania modułu.")),30000);
    window.addEventListener("officer-semantic-ready",ready);script.addEventListener("error",fail,{once:true});ready();
  })
}

export default function SemanticCoach({questions,progress,onRate,onExit}){
  const [q,setQ]=useState(()=>pick(questions,progress));
  const [phase,setPhase]=useState("ready"),[text,setText]=useState(""),[interim,setInterim]=useState("");
  const [start,setStart]=useState(null),[elapsed,setElapsed]=useState(0),[mic,setMic]=useState(false),[micOk,setMicOk]=useState(false),[micErr,setMicErr]=useState("");
  const [model,setModel]=useState("idle"),[modelPct,setModelPct]=useState(0),[modelErr,setModelErr]=useState(""),[busy,setBusy]=useState(false),[result,setResult]=useState(null),[source,setSource]=useState(false);
  const rec=useRef(null);
  const pts=useMemo(()=>q?chunks(q):[],[q]);
  const keyPct=pts.length?Math.round(pts.reduce((a,p)=>a+lexical(text,p),0)/pts.length*100):0;
  const hybridPct=result?.length?Math.round(result.reduce((a,x)=>a+x.hybrid,0)/result.length*100):0;
  const semanticPct=result?.length?Math.round(result.reduce((a,x)=>a+(x.semantic??x.lexical),0)/result.length*100):0;

  useEffect(()=>{setMicOk(Boolean(window.SpeechRecognition||window.webkitSpeechRecognition));return()=>rec.current?.abort()},[]);
  useEffect(()=>{if(phase!=="answering"||start===null)return;const tick=()=>setElapsed(Math.floor((Date.now()-start)/1000));tick();const id=setInterval(tick,250);return()=>clearInterval(id)},[phase,start]);
  const progressCb=info=>{if(typeof info?.progress==="number")setModelPct(p=>Math.max(p,Math.round(info.progress)));if(info?.status==="ready")setModelPct(100)};

  async function prepare(){setModel("loading");setModelErr("");setModelPct(0);try{const e=await getEngine();await e.load(progressCb);setModel("ready");setModelPct(100)}catch(err){setModel("error");setModelErr(err?.message||"Model nie wystartował.")}}
  function recognition(){const C=window.SpeechRecognition||window.webkitSpeechRecognition;if(!C)return null;const r=new C();r.lang="pl-PL";r.continuous=true;r.interimResults=true;r.onresult=e=>{let f="",i="";for(let x=e.resultIndex;x<e.results.length;x++){const z=e.results[x];z.isFinal?f+=`${z[0].transcript} `:i+=z[0].transcript}if(f)setText(v=>`${v} ${f}`.replace(/\s+/g," ").trim());setInterim(i)};r.onerror=()=>{setMic(false);setMicErr("Mikrofon został przerwany — możesz poprawić tekst ręcznie.")};r.onend=()=>setMic(false);return r}
  function begin(withMic){setText("");setInterim("");setResult(null);setSource(false);setElapsed(0);setStart(Date.now());setPhase("answering");setMicErr("");if(!withMic)return;const r=recognition();if(!r){setMicErr("Ta przeglądarka nie udostępnia rozpoznawania mowy.");return}rec.current=r;try{r.start();setMic(true)}catch{setMicErr("Nie udało się uruchomić mikrofonu.")}}
  function finish(){rec.current?.stop();rec.current=null;setMic(false);setInterim("");setStart(null);setPhase("review")}
  async function analyze(){if(!text.trim()||!pts.length)return;setBusy(true);setResult(null);setModelErr("");try{const e=await getEngine();if(model!=="ready"){setModel("loading");await e.load(progressCb);setModel("ready");setModelPct(100)}const out=await e.score(text,pts,progressCb);setResult(pts.map((point,i)=>{const l=lexical(text,point),s=semScore(out.similarities[i]??0),h=Math.max(s*.76+l*.24,l*.9);return{point,lexical:l,semantic:s,hybrid:Math.max(0,Math.min(1,h)),paraphrase:s>=.58&&s-l>=.22,numeric:mismatch(point,text)}}))}catch(err){setModel("error");setModelErr(`Semantyka nie zadziałała — używam matchera słów. ${err?.message||""}`);setResult(pts.map(point=>{const l=lexical(text,point);return{point,lexical:l,semantic:null,hybrid:l,paraphrase:false,numeric:mismatch(point,text)}}))}finally{setBusy(false)}}
  function next(){rec.current?.abort();rec.current=null;setQ(pick(questions,progress,q?.id));setPhase("ready");setText("");setInterim("");setResult(null);setSource(false);setElapsed(0);setStart(null);setMic(false);setMicErr("")}

  if(!q)return <div className="p-6">Brak pytań teoretycznych.</div>;
  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><button onClick={onExit} className="rounded-xl border border-neutral-700 px-4 py-2 text-sm font-bold">← Menu Etapu II</button><span className="rounded-full border border-sky-900/60 bg-sky-950/20 px-3 py-1.5 font-mono text-[10px] font-black text-sky-200">BETA // SEMANTYKA LOKALNA</span></div>
    <section className="rounded-[1.75rem] border border-sky-900/50 bg-[#101719] p-5 sm:p-7"><div className="text-xs text-[#82979a]">TEORIA • {q.category}</div><h1 className="mt-3 text-2xl font-black leading-tight sm:text-4xl">{q.question}</h1><p className="mt-3 text-sm leading-6 text-[#9cabad]">Odpowiadaj własnymi słowami. Model porównuje znaczenie, ale wzorcem pozostaje wyłącznie odpowiedź źródłowa.</p></section>
    <section className="rounded-2xl border border-[#30464a] bg-[#0c1214] p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><b>Paraphrase Multilingual MiniLM</b><p className="mt-1 max-w-2xl text-sm text-[#8fa0a3]">Pierwsze uruchomienie pobiera ok. 135 MB. Później pliki mogą działać z cache. Brak płatnego API.</p></div><div className="min-w-40 rounded-xl border border-[#30464a] bg-black/20 p-3 text-xs"><div className="flex justify-between"><span>Status</span><b>{model==="ready"?"GOTOWY":model==="loading"?"ŁADOWANIE":model==="error"?"FALLBACK":"NIEURUCHOMIONY"}</b></div><div className="mt-2 h-2 rounded-full bg-[#172125]"><div className="h-2 rounded-full bg-sky-300" style={{width:`${model==="ready"?100:modelPct}%`}}/></div></div></div><div className="mt-4 flex gap-3"><button disabled={model==="loading"||model==="ready"} onClick={prepare} className="rounded-xl border border-sky-900/60 bg-sky-950/30 px-4 py-2.5 text-sm font-bold text-sky-100 disabled:opacity-50">{model==="ready"?"✓ Model gotowy":model==="loading"?"Pobieram model…":"Przygotuj model"}</button>{model==="error"&&<button onClick={prepare} className="rounded-xl border border-neutral-700 px-4 py-2.5 text-sm font-bold">Spróbuj ponownie</button>}</div>{modelErr&&<p className="mt-3 text-xs text-red-200">{modelErr}</p>}</section>
    {phase==="ready"&&<section className="rounded-2xl border border-[#34474a] bg-[#0f1517] p-5"><h2 className="font-bold">Odpowiedz naturalnie</h2><div className="mt-4 flex flex-wrap gap-3"><button disabled={!micOk} onClick={()=>begin(true)} className="rounded-xl bg-[#d9e7e7] px-5 py-3 text-sm font-black text-[#102022] disabled:opacity-40">🎙️ Mikrofon</button><button onClick={()=>begin(false)} className="rounded-xl border border-[#40565a] px-5 py-3 text-sm font-bold">Bez mikrofonu</button><button onClick={next} className="rounded-xl border border-neutral-700 px-5 py-3 text-sm font-bold">Losuj inne</button></div></section>}
    {phase==="answering"&&<section className="rounded-2xl border border-[#385358] bg-[#0d1517] p-5"><div className="flex justify-between"><b>Odpowiedź trwa</b><span className="font-mono text-3xl font-black">{fmt(elapsed)}</span></div><div className="mt-5 min-h-24 rounded-xl border border-[#2e4145] bg-black/20 p-4 text-sm leading-6">{text||interim?<>{text}{interim&&<span className="text-[#71868a]"> {interim}</span>}</>:<span className="text-[#66777a]">Czekam na odpowiedź…</span>}</div>{micErr&&<p className="mt-3 text-xs text-amber-200">{micErr}</p>}<div className="mt-4 flex gap-3"><button onClick={finish} className="rounded-xl bg-[#d9e7e7] px-5 py-3 text-sm font-black text-[#102022]">Zakończ</button>{mic&&<span className="self-center text-xs font-bold text-emerald-300">● mikrofon aktywny</span>}</div></section>}
    {phase==="review"&&<><section className="rounded-2xl border border-[#34474a] bg-[#0e1517] p-5"><div className="flex justify-between gap-3"><div><b>Transkrypcja</b><p className="mt-1 text-xs text-[#7f9093]">Popraw ewentualne błędy rozpoznawania mowy.</p></div><span className="font-mono text-xs">KEY {keyPct}%</span></div><textarea value={text} onChange={e=>{setText(e.target.value);setResult(null)}} rows={6} className="mt-4 w-full rounded-xl border border-[#304247] bg-black/20 p-4 text-sm leading-6 outline-none"/><div className="mt-4 flex flex-wrap gap-3"><button disabled={busy||!text.trim()} onClick={analyze} className="rounded-xl bg-sky-100 px-5 py-3 text-sm font-black text-[#102327] disabled:opacity-40">{busy?"Analizuję…":result?"Przelicz":"Analizuj znaczenie"}</button><button onClick={()=>{setPhase("ready");setText("");setResult(null)}} className="rounded-xl border border-neutral-700 px-4 py-3 text-sm font-bold">Powtórz</button></div></section>
    {busy&&<section className="rounded-2xl border border-sky-900/40 bg-sky-950/10 p-6 text-center"><b>Model porównuje znaczenie odpowiedzi…</b></section>}
    {result&&!busy&&<><section className="rounded-2xl border border-[#3b565b] bg-[#10191b] p-5"><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-black/20 p-4"><small>Hybryda</small><div className="text-3xl font-black">{hybridPct}%</div></div><div className="rounded-xl bg-black/20 p-4"><small>Znaczenie</small><div className="text-3xl font-black text-sky-200">{semanticPct}%</div></div><div className="rounded-xl bg-black/20 p-4"><small>Słowa kluczowe</small><div className="text-3xl font-black">{keyPct}%</div></div></div><p className="mt-4 text-xs text-[#809397]">Semantyka ma większą wagę, więc poprawna parafraza może zostać zaliczona mimo innych słów. Wynik jest treningowy.</p></section><div className="space-y-3">{result.map((x,i)=>{const[icon,label,cls]=stateFor(x.hybrid);return<section key={i} className={`rounded-2xl border p-4 ${cls}`}><div className="flex flex-wrap justify-between gap-2"><b>{icon} Punkt {i+1} — {label}</b><small>HYB {Math.round(x.hybrid*100)}% · SEM {x.semantic===null?"—":Math.round(x.semantic*100)+"%"} · KEY {Math.round(x.lexical*100)}%</small></div><p className="mt-3 text-sm leading-6">{x.point}</p>{x.paraphrase&&<span className="mt-3 inline-flex rounded-full border border-sky-800/50 px-3 py-1 text-xs font-bold text-sky-200">↔ Parafraza rozpoznana</span>}{x.numeric&&<p className="mt-3 text-xs text-amber-100">⚠ Liczba/data niepotwierdzona tekstowo — sprawdź ręcznie.</p>}</section>})}</div><section className="rounded-2xl border border-neutral-800 bg-neutral-900 p-5"><button onClick={()=>setSource(v=>!v)} className="rounded-xl border border-neutral-700 px-4 py-2 text-sm font-bold">{source?"Ukryj odpowiedź":"Pokaż pełną odpowiedź źródłową"}</button>{source&&<p className="mt-4 whitespace-pre-line text-sm leading-6 text-neutral-300">{q.fullAnswer}</p>}</section><section className="rounded-2xl border border-[#34474a] bg-[#0f1517] p-5"><b>Jak poszłoby Ci przed komisją?</b><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-5">{ratings.map(([v,l])=><button key={v} onClick={()=>{onRate(q.id,v);next()}} className="rounded-xl border border-[#3d5054] bg-black/20 px-3 py-3 text-left text-xs font-bold"><b className="mr-2 text-base">{v}</b>{l}</button>)}</div></section></>}
    </>}
  </div>
}
